version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - sec-network
    volumes:
      - ./fraud_model.pkl:/app/fraud_model.pkl

  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - sec-network

networks:
  sec-network:
    driver: bridge
